language: java
sudo: false
install: mvn --version
script: mvn --settings settings.xml clean -DskipITs deploy -q
branches:
  only:
  - master
notifications:
  email:
  - infra@sayhello.com
  slack:
    secure: aRgIgBV/1ZenkdCkXQ0xniTvgV6SWyLCb9dxoAPr3uUe+Tsy3B3Bso2ZJRPnef6kPtfZQX8JSAoVBaGosBVRMKJ2IDgb8KxfTKqQT4NKF+UJjOkGYY6C81A+Y5nl5Wt7xFjR8o0pn/C1kn0KS4gittVZcxB6BsFy2HYK1SPNd3w=
jdk:
- oraclejdk7
env:
  global:
  - secure: ZtcabJIbdoPJSX8tHU6Hocj1dknD/UxATnqvvVo3RK9CwWYlzEbO/3AyAqul78ythMOnvouU9dIFoxjxb4lek1nsd3dvSix7zNa4YVDvcj0+uV/IBl12OqTO2RnxlP5MPIeRzkrhs0vg1OfvxquMizBcBdF7MbwmdUtL1g1IA3A=
  - secure: Ed/gOoioqi7oacM+HpYsBF8nfXE6sd3Y99ZtNKg4mTrNUB9adF9jijv2B669TP+L/QXNoMvZizF7Cq+JFxjgH39pEMuMJfMsci2upxEtymZRbWKv3Kr6wM8AF7Jdyinf71RkIZC3VffKOluQ6vSFx1O51oVuSyrjyGxOYraPKWI=
